### ISSUE TITLE
Fetching data via SPS API

### ISSUE THREAD

**Issue by thisguy002** [blocktradesdevs/steem#102]
Is sps api plugin working only with curl or I can use the api endpoint to fetch data for the web app? I'm using the endpoint that you suggested (specifically `http://sps-blocktrades-testnet-api.blocktrades.info:8090/list_proposals?start=block&order_by=by_creator&order_direction=direction_ascending&limit=100&status=all`) via http call and get `code: -32000, message: End Of File:stringstream` error.

Would appreciate the help. Your work is amazing.
P.S. The calls are made using Typescript + Angular.

**Comment by dnotestein** [comment]
From our testing, it's not possible to fetch the data with just a URL (the endpoint is only for json-rpc and ignores the url query parameters). Your http request needs to put the method name, id, and parameters in the http request body.

**Comment by bwsdeveloper** [comment]
Here is an example of valid RPC call:
```
{"jsonrpc":"2.0","id":"2","method":"sps_api.list_proposals",
 "params":{"start":"block", "order_by":"by_creator", "order_direction":"direction_ascending","limit":100,"status":"all"}}
```
