### ISSUE TITLE
Object ID for Proposals Used in Protocol

### ISSUE THREAD

**Issue by mvandeberg** [blocktradesdevs/steem#129]
It appears that the internal object id is being using as a canonical reference to proposals. 

https://github.com/blocktradesdevs/steem/blob/4ab8ba9ca0f4eefba1b3447dc6aaa81714aa92fc/libraries/protocol/include/steem/protocol/sps_operations.hpp#L31-L43

Object ids are an implementation detail of the backing object database and should not be used in the blockchain protocol. Chainbase changed the implementation of object ids and that may change again.

In an effort to keep as much of the existing code in place as possible, I propose this workaround. Create a duplicate field, `int64_t proposal_id`, that copies the internal object id on creation and is used as the canonical identifier. If, in the future, the object id implementation is changed we can implement a system that generates proposal ids in an identical manner to preserve backwards compatibility. UIs properly using the `proposal_id` field would not need to upgrade to continue functioning.

**Comment by dnotestein** [comment]
As I previously expressed in our design call, I don't agree with idea that ids generated by a database are an "implementation detail" of the database used to generate them. Pretty much every database I've ever worked with has a way to generate sequential integer ids for new records. I am aware of cases where there's a desire not to expose such ids to the outside world (to potentially avoid revealing information), but I don't think that logic applies here.

Nevertheless, to continue to follow the convention currently being used by Steem code, we can make the workaround change suggested above.
