### ISSUE TITLE
Implement/adjust unit tests to verify SPS related operations

### ISSUE THREAD

**Issue by bwsdeveloper** [blocktradesdevs/steem#22]
Unit testing code needs to be adjusted, also specific scenarios implemented for create_proposal_operation, update_proposal_votes_operation, remove_proposal_operation.

Changes to be done inside `t_proposal_database_fixture` and dedicated SPS unit tests.

**Comment by sianodel** [comment]
Added tests:
Test : "create_proposal_000"       - "Testing create proposal opration arguments validation - all args are ok"
Test : "create_proposal_001"       - "Testing create proposal opration arguments validation - invalid creator"
Test : "create_proposal_002"       - "Testing create proposal opration arguments validation - invalid receiver"
Test : "create_proposal_003"       - "Testing create proposal opration arguments validation - invalid start date"
Test : "create_proposal_004"       - "Testing create proposal opration arguments validation - invalid end date"
Test : "create_proposal_005"       - "Testing create proposal opration arguments validation - invalid subject(empty)"
Test : "create_proposal_006"       - "Testing create proposal opration arguments validation - invalid subject(too long)"
Test : "create_proposal_007"       - "Testing create proposal authorization test"
Test : "update_proposal_votes_000" - "Testing update proposal votes opration arguments validation - all ok (approve true)"
Test : "update_proposal_votes_001" - "Testing update proposal votes opration arguments validation - all ok (approve false)"
Test : "update_proposal_votes_002" - "Testing update proposal votes opration arguments validation - all ok (empty array)"
Test : "update_proposal_votes_003" - "Testing update proposal votes opration arguments validation - all ok (array with negative digits)"
Test : "update_proposal_votes_004" - "Testing update proposal votes opration arguments validation - invalid voter"
Test : "update_proposal_votes_005" - "Testing update proposal votes opration arguments validation - invalid id array (array with greater number of digits than allowed)"
Test : "update_proposal_votes_006" - "Testing update proposal votes authorization test"
Test : "remove_proposal_000"       - "Testing remove proposal basic verification operation - proposal removal (only one)."
Test : "remove_proposal_001"       - "Testing remove proposal basic verification operation - proposal removal (one from many)."
Test : "remove_proposal_002"       - "Testing remove proposal basic verification operation - proposal removal (n from many in two steps)."
Test : "remove_proposal_003"       - "Testing remove proposal basic verification operation - proper proposal deletion check (one at time)."
Test : "remove_proposal_004"       - "Testing remove proposal basic verification operation - proper proposal deletion check (two at one time)."
Test : "remove_proposal_005"       - "Testing remove proposal basic verification operation - proposal with votes removal (only one)."
Test : "remove_proposal_006"       - "Testing remove proposal basic verification operation - remove proposal with votes and one voteless at same time."
Test : "remove_proposal_007"       - "Testing remove proposal basic verification operation - remove proposals with votes at same time."
Test : "remove_proposal_008"       - "Testing remove proposal opration arguments validation - all ok"
Test : "remove_proposal_009"       - "Testing remove proposal opration arguments validation - invalid deleter"
Test : "remove_proposal_010"       - "Testing remove proposal opration arguments validation - invalid array(empty array)"
Test : "remove_proposal_011"       - "Testing remove proposal opration arguments validation - invalid array(array with greater number of digits than allowed)"
Test : "remove_proposal_012"       - "Testing remove proposal authorization test"
