### ISSUE TITLE
Consensus Information in SPS Plugin

### ISSUE THREAD

**Issue by mvandeberg** [blocktradesdevs/steem#46]
I understand the allure of putting the bulk of the SPS implementation in a plugin for organization, but consensus information in plugins is an anti-pattern. Plugins are designed to be organized in an acyclic-digraph.

There is an implicit requirement that the chain plugin will run all consensus information. It needs to add the following line, `APPBASE_PLUGIN_REQUIRES( (sps_plugin) )` or else a node could chose not to run the sps plugin and will eventually fork when they disagree on token balance.

At the same time, the sps plugin needs access to the database, which is only provided through the chain plugin (on purpose). The business logic that exists in the sps plugin should just be moved to a separate source file in the chain directory.

**Comment by vogel76** [comment]
sps_plugin is mandatory one and it is loaded by default. Also there is no dependency cycle between plugins - sps_plugin depends on chain_plugin like also chain module but not otherwise.

**Comment by mvandeberg** [comment]
This sets a dangerous precedent. All consensus actions need to occur in a deterministic action. While tying consensus state changes to signals is deterministic, the order of those actions is not always clear. One plugin may not be problematic, but this pattern opens us up to subtle consensus breaking bugs when more are added. Furthermore, as the longest active developer on Steem, I rely heavily on the fact that consensus breaking changes only live in protocol and chain. This is a huge benefit when fixing bugs and reviewing code to help compartmentalize my thoughts. There is no good reason to change how we add to consensus state right now. I ask you to reconsider this design to conform with how the rest of the consensus state is implemented.

**Comment by vogel76** [comment]
Having consensus code at one place is really good reason. Let's change it then and move code into libraries chain, like also eliminate dedicated signal.

**Comment by vogel76** [comment]
sps_plugin future will be determined soon so let's wait a little with removing it - here is a remainder:
issue #56
