### ISSUE TITLE
Create test scenario to verify proposal payments

### ISSUE THREAD

**Issue by vogel76** [blocktradesdevs/steem#63]
Given scenario shall

- create few proposals. 
- vote on them to show differences in asset distribution (depending on collected votes)
- wait for proposal payment phase
- verify (using account history and by checking regular account balance) that given accounts have been correctly paid.

**Comment by dkedzierski** [comment]
* Support for Debug API was added to the steempy lib.
* Works on test in progress

**Comment by dkedzierski** [comment]
First test is ready and working as expected. More test to come.

**Comment by dkedzierski** [comment]
Works are continued in dk-issue63-cont

**Comment by vogel76** [comment]
Done at PR:
https://github.com/blocktradesdevs/steem/pull/133
