### ISSUE TITLE
active parameter in the list_* calls is not intuitive

### ISSUE THREAD

**Issue by emre** [blocktradesdevs/steem#66]
in the [SPS API Plugin](https://github.com/blocktradesdevs/steem/wiki/SPS-API-Plugin) `list_proposals` and `list_voter_proposals` have a parameter named `active` where one can pass `1`, `0`, or `-1`. It sounds like a boolean field by its naming, however, it's not.

Instead of that I propose to change that parameter's name to the `status` where options can be String. 

- active
- inactive
- all

**Comment by bwsdeveloper** [comment]
I like this idea, enum values are much more readable.

**Comment by bwsdeveloper** [comment]
Merged:
https://github.com/blocktradesdevs/steem/commit/2e5779bdd048d093c6cc511f16319a0b78d6eda7
https://github.com/blocktradesdevs/steem/pull/71
