### ISSUE TITLE
[cli_wallet] list returned by list_voter_proposal is wrong

### ISSUE THREAD

**Issue by Gandalf-the-Grey** [blocktradesdevs/steem#67]
Expected behavior:
`list_voter_proposal` should list proposals I voted for

`cli_wallet` command:
`list_voter_proposals gtg creator asc 2 -1`
sends request to steemd:
`{"jsonrpc":"2.0","id":18,"method":"call","params":["condenser_api","list_voter_proposals",["gtg","by_creator","direction_ascending",2,-1]]}`
which gives wrong result (i.e. list proposals that I haven't voted for)

**Comment by bwsdeveloper** [comment]
Fixed at 
https://github.com/blocktradesdevs/steem/pull/68
