### ISSUE TITLE
Define dedicated virtual operation to deposit payments to given proposal-account

### ISSUE THREAD

**Issue by vogel76** [blocktradesdevs/steem#7]
Proposal processing shall lead to pay calculated amount of SBD from `treasury` account to the account associated to given proposal. This action shall be executed as virtual operation, being instantiated and executed at consensus level. Such scheme will allow logging such payments via regular Account History plugin.

We should consider adding dedicated checks to disallow execution of this operation during regular transaction processing. This operation can be executed only by consensus code.

**Comment by khumble00101** [comment]
So maybe I'm just dumb to all this and I'm so sorry if I am but why are the same numbers in my files posted on this website talking a verified payment?? I've never received a payment for anything and also I've never signed up for anything. I post videos of encouragement and write poetry but if someone could please help me understand id appreciate it. Also I can give proof if you'd like. Just not sure why my fingerprint SHA 1 SHA256  and id.l Numbers keep popping up.
