### ISSUE TITLE
`virtual_sbd_supply` is weird

### ISSUE THREAD

**Issue by mvandeberg** [blocktradesdevs/steem#75]
I am not sure how else to describe what I am observing other than, "it's weird".

As best I can tell, the `virtual_sbd_supply` field of the `dynamic_global_properties` object is only used for making the invariant checks succeed. But that isn't entirely true because the init_sbd_supply added in genesis options is intended to be used for forks of the Steem Blockchain. The real problem it is trying to solve, is how is there a virtual supply of STEEM when there is no price feed. The answer come up with here is that we don't count the initial supply. In which case, maybe the field should be called `init_sbd_supply` instead of `virtual_sbd_supply`. This field, as written, exists in mainnet builds and will show up in API responses. The name should be self-descriptive, which I currently don't believe is the case.

Another solution is to only have the field exist in test net builds. However, in test net builds, a default price feed is already set, which means you could just add this value to the `current_sbd_supply` and make the sbd genesis supply a testnet only feature. I am partial to the second solution because it seems the cleanest. The goal here is not to make launching Steem forks easier, but to make testing Steem easier.

**Comment by dnotestein** [comment]
If virtual_sbd_supply is really init_sbd_supply, change the name appropriately. I was also wondering what the name meant (I just asked internally though, not here).  I disagree with the testnet only approach, however.

**Comment by vogel76** [comment]
Done in PR:
https://github.com/blocktradesdevs/steem/pull/93
