### ISSUE TITLE
Proposal payment and cleanup should be automated actions

### ISSUE THREAD

**Issue by mvandeberg** [blocktradesdevs/steem#76]
Both of these functions are O(n) and could, in the right circumstances, lead to delays in block propagation. Deleting a proposal that has a high quantity of votes can be used quite easily to cause a significant amount of per block processing. This use case is the precise reason why automated actions were developed. While they were created to be used with SMTs, the design leveraged previous blockchain development experience to create a system that could replace all existing per block processing. The same is true with the per block processing added with the Steem Proposal System.

I strongly recommend that per block processing and non-constant time operations added for SPS be replaced with required automated actions. Developing automated actions is quite simple, and I would be happy to give a primer/expand [documentation](https://github.com/steemit/steem/pull/3259/commits/ce2fa90381b1e44d532cc9ce86f44e614276933f) as needed.

**Comment by bwsdeveloper** [comment]
We would like to leave this implementation at the end of development process to complete required functionality. To avoid uncontrolled delays in block production, we just remove inactive proposal cleanup.

**Comment by mvandeberg** [comment]
This is not limited to removal of inactive proposals, but deletion of current proposals by the owner and payment of proposals, both of which are required functionality for SPS.

**Comment by Mariusz-Trela** [comment]
Removing elements depends on `sps_remove_threshold` threshold. Default value of this threshold is 200, it means that only 200 objects can be removed during 1 block. In the future this threshold will be changed to automatic actions.
