### ISSUE TITLE
SPS object types not declared properly

### ISSUE THREAD

**Issue by mvandeberg** [blocktradesdevs/steem#77]
All SPS object types should be declared in `steem_object_types.hpp`

**Comment by bwsdeveloper** [comment]
I suppose your intention was to include them in `object_type` enum ? If so what is purpose for this enum type since seems it is not used in the project.

**Comment by mvandeberg** [comment]
The enum defines an internal ID where the index will live in chainbase. As it is currently implemented, the objects reside in the plugin ID space, not the consensus object ID space.

**Comment by vogel76** [comment]
Done in PR:
https://github.com/blocktradesdevs/steem/pull/98
