### ISSUE TITLE
Use case: As an active community member I'd like to know what I'm voting for

### ISSUE THREAD

**Issue by Gandalf-the-Grey** [blocktradesdevs/steem#84]
I was hoping that `list_voter_proposal` would be the right thing to achieve that
If yes, then #67 should be re-opened

**Comment by dkedzierski** [comment]
I think that "voter" argument of this method is confusing. It should be renamed to "start" to be consistent with the rest of the list_ methods.

I think that new method can be added: get_voter_proposals which will return only proposals voted by given voter.

**Comment by bwsdeveloper** [comment]
`list_voter_proposals` method has been implemented similary to other `list_` methods provided by steem API. That's reason why it starts listing votes from entries associated to voter specified in the method parameters.
This condition is not strict - it allows to retrieve votes for other voters too by iterating whole requested range what makes this method more useful - frontend developer can easily filterout additional items by comparing returned voter to given one and display only votes specific to single account.

Behavior is specified here:
https://github.com/blocktradesdevs/steem/wiki/SPS-API-Plugin#list_voter_proposals

I agree to change parameter `voter` to `start` and this way make this method even more similar to the `list_` family.

**Comment by vogel76** [comment]
We have changed parameter name to `start` for better compatibility to other `list_` methods. For other API changes we'd like to wait for frontend developers feedback to adjust the API to their needs.
