### ISSUE TITLE
Bug: It's possible to set negative values for daily_pay on proposal creation

### ISSUE THREAD

**Issue by emre** [blocktradesdevs/steem#90]
As a proposal creator, If I enter the `daily_pay` field as a negative value, I see that the steemd accepts the transaction as a valid transaction.

I have pushed an example Proposal object to the public testnet with id 6.

You can see it with this cURL command:

```
curl -s --data '{"jsonrpc":"2.0","id":"2","method":"sps_api.find_proposals", "params" : {"id_set" : [6]}}' http://sps-blocktrades-testnet-api.blocktrades.info:8090
```

I think, `create_proposal_operation::validate()` should be updated with an additional check on this.

#### Steps to reproduce

- Create a proposal with a negative `daily_pay` balance. (Ex: -10000 S(T)BD)
- Confirm if the transaction is accepted.
- Check the negative value with `sps_api.find_proposals` RPC call.

**Comment by vogel76** [comment]
Fixed at PR:
https://github.com/blocktradesdevs/steem/pull/95

**Comment by Nil1995-15** [comment]
😇😇
