### ISSUE TITLE
Changing treasury account auths does not lock out account properly.

### ISSUE THREAD

**Issue by mvandeberg** [blocktradesdevs/steem#94]
https://github.com/blocktradesdevs/steem/blob/704f8aa6761e549650b3f28bd465943dcd1dc026/libraries/chain/database.cpp#L5084-L5085

`account_auths` and `key_auths` in each authority must also be cleared or else the existing keys will continue to work on the account. Should we do the same with the posting authority as well making the account like the null account without clearing of balances?

**Comment by dnotestein** [comment]
It was my plan to just set the keys to 0 and set the recovery account to null or something similar, like to itself, as I was told that null means top witness becomes recover agent (i.e. give up control of the account via normal wallet mechanisms). Is there some reason to write code to do it instead (maybe wallet doesn't allow keys to be set to 0)? AFAIK, the account has no "value" until funds are put in it manually, as there is no automated funding source in the original release.

**Comment by mvandeberg** [comment]
If we write code that changes the owner key then the past owner key is never added to the account's history and thus never recoverable (regardless of the set recovery partner). This hardfork makes this account a "special" Steem account similar to `@temp` or `@null`.

You may be right that the account has no "value" until there are funds added, but the SPS can begin paying out as soon as funds are added after the fork takes place. However, it only makes sense to add funds after the keys are properly set. We might as well set them during the hardfork as to make the launch of the SPS as smooth as possible.

**Comment by Mariusz-Trela** [comment]
Added `auth.posting.weight_threshold = 1` in order to consistency

**Comment by vogel76** [comment]
Done in https://github.com/blocktradesdevs/steem/pull/114
